
# -*- coding: utf-8 -*-

_comarcas = {
    "ac": {"sigla": "AC", "nome": "Acre",
           "comarcas": ["Acrelândia", "Assis Brasil", "Brasiléia", "Bujari",
                        "Capixaba", "Cruzeiro do Sul", "Epitaciolândia",
                        "Feijó", "Jordão", "Mâncio Lima", "Manoel Urbano",
                        "Marechal Thaumaturgo", "Plácido de Castro",
                        "Porto Acre", "Porto Walter", "Rio Branco",
                        "Rodrigues Alves", "Santa Rosa do Purus",
                        "Senador Guiomard", "Sena Madureira", "Tarauacá",
                        "Xapuri"]},
    "al": {"sigla": "AL", "nome": "Alagoas",
           "comarcas": ["Água Branca", "Anadia", "Arapiraca", "Atalaia",
                        "Batalha", "Boca da Mata", "Cacimbinhas", "Cajueiro",
                        "Campo Alegre", "Canapi", "Capela",
                        "Colônia Leopoldina", "Coruripe", "Delmiro Gouveia",
                        "Feira Grande", "Flexeiras", "Girau do Ponciano",
                        "Igaci", "Igreja Nova", "Joaquim Gomes", "Junqueiro",
                        "Limoeiro de Anadia", "Maceió", "Major Isidoro",
                        "Maragogi", "Maravilha", "Marechal Deodoro",
                        "Maribondo", "Mata Grande", "Matriz de Camaragibe",
                        "Messias", "Murici", "Novo Lino",
                        "Olho d'Água das Flores", "Palmeira dos Índios",
                        "Pão de Açúcar", "Paripueira", "Passo de Camaragibe",
                        "Paulo Jacinto", "Penedo", "Piaçabuçu", "Pilar",
                        "Piranhas", "Porto Calvo", "Porto de Pedras",
                        "Porto Real do Colégio", "Quebrangulo", "Rio Largo",
                        "Santa Luzia do Norte", "Santana do Ipanema",
                        "São Brás", "São José da Laje", "São José da Tapera",
                        "São Luiz do Quitunde", "São Miguel dos Campos",
                        "São Sebastião", "Taquarana", "Teotônio Vilela",
                        "Traipu", "União dos Palmares", "Viçosa"]},
    "am": {"sigla": "AM", "nome": "Amazonas",
           "comarcas": ["Alvarães", "Amaturá", "Anamã", "Anori", "Apui",
                        "Atalaia do Norte", "Autazes", "Barcelos",
                        "Barreirinha", "Benjamin Constant", "Beruri",
                        "Boa Vista do Ramos", "Boca do Acre", "Borba",
                        "Caapiranga", "Canutama", "Carauari", "Careiro",
                        "Careiro Castanho", "Careiro da Várzea", "Coari",
                        "Codajás", "Eirunepé", "Envira", "Fonte Boa",
                        "Guajará", "Humaitá", "Ipixuna", "Iranduba",
                        "Itacoatiara", "Itamarati", "Itapiranga", "Japurá",
                        "Juruá", "Jutaí", "Lábrea", "Manacapuru", "Manaquiri",
                        "Manaus", "Manicoré", "Maraã", "Maués", "Nhamundá",
                        "Nova Olinda do Norte", "Novo Airão", "Novo Aripuanã",
                        "Parintins", "Pauini", "Presidente Figueiredo",
                        "Rio Preto da Eva", "Santa Isabel do Rio",
                        "Santa Isabel do Rio Negro", "Santo Antonio do Içá",
                        "São Gabriel da Cachoeira", "São Paulo de Olivença",
                        "São Sebastião do Uatumã", "Silves", "Tabatinga",
                        "Tapauá", "Tefé", "Uarini", "Urucará", "Urucurituba"]},
    "ap": {"sigla": "AP", "nome": "Amapá",
           "comarcas": ["Amapá", "Calçoene", "Ferreira Gomes",
                        "Laranjal do Jari", "Macapá", "Mazagão", "Oiapoque",
                        "Pedra Branca do Amapari", "Porto Grande", "Santana",
                        "Serra do Navio", "Tartarugalzinho",
                        "Vitória do Jari"]},
    "ba": {"sigla": "BA", "nome": "Bahia",
           "comarcas": ["Alagoinhas", "Amargosa", "Amélia Rodrigues",
                        "América Dourada", "Anagé", "Andaraí", "Angical",
                        "Antas", "Aporá", "Araci", "Aurelino Leal",
                        "Baianópolis", "Baixa Grande", "Barra",
                        "Barra da Estiva", "Barra do Choça", "Barra do Mendes",
                        "Barreiras", "Belmonte", "Belo Campo",
                        "Boa Vista do Tupim", "Bom Jesus da Lapa", "Boquira",
                        "Botuporã", "Brejões", "Brotas de Macaúbas", "Brumado",
                        "Buerarema", "Cachoeira", "Caculé", "Caetité",
                        "Caldeirão Grande", "Camacã", "Camacan", "Camaçari",
                        "Camamu", "Campo Alegre de Lourdes", "Campo Formoso",
                        "Canarana", "Canavieiras", "Candeias", "Cândido Sales",
                        "Cansanção", "Canudos", "Capela do Alto Alegre",
                        "Capim Grosso", "Caravelas", "Carinhanha", "Casa Nova",
                        "Castro Alves", "Catu", "Central", "Chorrochó",
                        "Cícero Dantas", "Cipó", "Coaraci", "Cocos",
                        "Conceição do Almeida", "Conceição do Coité",
                        "Conceição do Jacuípe", "Conde", "Condeúba",
                        "Coração de Maria", "Coribe", "Correntina", "Cotegipe",
                        "Cristópolis", "Cruz das Almas", "Curaçá",
                        "Dias D’ávila", "Encruzilhada", "Entre Rios",
                        "Esplanada", "Euclides da Cunha", "Eunápolis",
                        "Feira de Santana", "Formosa do Rio Preto", "Gandu",
                        "Gavião", "Gentio do Ouro", "Glória",
                        "Governador Lomanto Júnior", "Governador Mangabeira",
                        "Guanambi", "Guaratinga", "Iaçu", "Ibicaraí",
                        "Ibiquera", "Ibirapitanga", "Ibirapuã", "Ibirataia",
                        "Ibitiara", "Ibititá", "Ibotirama", "Ichu", "Igaporã",
                        "Iguaí", "Ilhéus", "Inhambupe", "Ipiaú", "Ipirá",
                        "Iramaia", "Iraquara", "Irará", "Irecê", "Itabela",
                        "Itaberaba", "Itabuna", "Itacaré", "Itaeté", "Itagi",
                        "Itagibá", "Itajuípe", "Itamaraju", "Itamari",
                        "Itambé", "Itanhém", "Itaparica", "Itapetinga",
                        "Itapicuru", "Itapitanga", "Itaquara", "Itarantim",
                        "Itiúba", "Itororó", "Ituaçu", "Ituberá", "Iuiu",
                        "Jacaraci", "Jacobina", "Jaguaquara", "Jaguarari",
                        "Jaguaripe", "Jequié", "Jeremoabo", "Jiquiriçá",
                        "Jitaúna", "João Dourado", "Juazeiro", "Jussara",
                        "Laje", "Lapão", "Lauro de Freitas", "Lençóis",
                        "Licínio de Almeida", "Livramento de Nossa Senhora",
                        "Luís Eduardo Magalhães", "Macarani", "Macaúbas",
                        "Macururé", "Madre de Deus", "Mairi", "Malhada",
                        "Maracás", "Maragogipe", "Marcionílio Souza",
                        "Mata de São João", "Medeiros Neto", "Miguel Calmon",
                        "Milagres", "Monte Santo", "Morpará",
                        "Morro do Chapéu", "Mortugaba", "Mucuri", "Mundo Novo",
                        "Muritiba", "Mutuípe", "Nazaré", "Nilo Peçanha",
                        "Nordestina", "Nova Fátima", "Nova Soure",
                        "Nova Viçosa", "Olindina", "Oliveira dos Brejinhos",
                        "Palmas de Monte Alto", "Paramirim", "Paripiranga",
                        "Paulo Afonso", "Pé de Serra", "Piatã", "Pilão Arcado",
                        "Pindaí", "Pindobaçu", "Piritiba", "Planalto",
                        "Poções", "Pojuca", "Porto Seguro", "Potiraguá",
                        "Prado", "Presidente Dutra",
                        "Presidente Jânio Quadros", "Queimadas", "Quixabeira",
                        "Remanso", "Retirolândia", "Riachão das Neves",
                        "Riachão do Jacuípe", "Riacho de Santana",
                        "Ribeira do Pombal", "Rio do Antônio", "Rio Real",
                        "Rodelas", "Ruy Barbosa", "Salvador", "Santa Bárbara",
                        "Santa Cruz Cabrália", "Santa Inês", "Santaluz",
                        "Santa Luz", "Santa Maria da Vitória", "Santana",
                        "Santa Rita de Cássia", "Santa Teresinha",
                        "Santa Terezinha", "Santo Amaro",
                        "Santo Antônio de Jesus", "Santo Estêvão",
                        "São Desidério", "São Domingos", "São Felipe",
                        "São Félix", "São Francisco do Conde", "São Gabriel",
                        "São Gonçalo dos Campos", "São José do Jacuípe",
                        "São Sebastião do Passé", "Sapeaçu", "Sátiro Dias",
                        "Saúde", "Seabra", "Senhor do Bonfim", "Sento Sé",
                        "Serra Dourada", "Serrinha", "Serrolândia",
                        "Simões Filho", "Sobradinho", "Souto Soares",
                        "Tanhaçu", "Tanque Novo", "Taperoá",
                        "Teixeira de Freitas", "Teodoro Sampaio",
                        "Teofilândia", "Terra Nova", "Tremedal", "Tucano",
                        "Uauá", "Ubaíra", "Ubaitaba", "Ubatã", "Uibaí", "Una",
                        "Urandi", "Uruçuca", "Utinga", "Valença", "Valente",
                        "Várzea do Poço", "Vitória da Conquista", "Wanderley",
                        "Wenceslau Guimarães", "Xique-Xique"]},
    "ce": {"sigla": "CE", "nome": "Ceará",
           "comarcas": ["Acarape", "Acaraú", "Acopiara", "Aiuaba",
                        "Alcântaras", "Alto Santo", "Amontada",
                        "Antonina do Norte", "Aquiraz", "Aracati", "Aracoiaba",
                        "Ararendá", "Araripe", "Aratuba", "Arneiroz", "Assaré",
                        "Aurora", "Baixio", "Banabuiu", "Barbalha", "Barreira",
                        "Barro", "Barroquinha", "Baturité", "Beberibe",
                        "Bela Cruz", "Boa Viagem", "Brejo Santo", "Camocim",
                        "Campo Sales", "Campos Sales", "Canindé", "Capistrano",
                        "Caridade", "Cariré", "Caririaçu", "Cariús",
                        "Carnaúbal", "Cascavel", "Catarina", "Catunda",
                        "Caucaia", "Cedro", "Chaval", "Choró Limão",
                        "Chorozinho", "Coreaú", "Crateús", "Crato", "Croatá",
                        "Cruz", "Deputado Irapuan Pinheiro", "Ererê",
                        "Eusébio", "Farias Brito", "Forquilha", "Fortaleza",
                        "Fortim", "Frecheirinha", "Freicheirinha",
                        "General Sampaio", "Graça", "Granja", "Groaíras",
                        "Guaiúba", "Guaraciaba do Norte", "Guaramiranga",
                        "Hidrolândia", "Horizonte", "Ibiapina", "Ibicuitinga",
                        "Icapuí", "Icó", "Iguatu", "Independência",
                        "Ipaporanga", "Ipaumirim", "Ipu", "Ipueiras",
                        "Iracema", "Irauçuba", "Itaitinga", "Itapajé",
                        "Itapipoca", "Itapiúna", "Itarema", "Itatira",
                        "Jaguaretama", "Jaguaribara", "Jaguaribe",
                        "Jaguaruana", "Jardim", "Jati",
                        "Jijoca de Jericoacoara", "Juazeiro do Norte", "Jucás",
                        "Lavras da Mangabeira", "Limoeiro do Norte",
                        "Madalena", "Maracanaú", "Maranguape", "Marco",
                        "Martinópole", "Massapê", "Mauriti", "Meruoca",
                        "Milagres", "Milhã", "Miraima", "Missão Velha",
                        "Mombaça", "Monsenhor Tabosa", "Morada Nova",
                        "Moraújo", "Morrinhos", "Mucambo", "Mulungu",
                        "Nova Olinda", "Nova Russas", "Novo Oriente", "Ocara",
                        "Orós", "Pacajus", "Pacatuba", "Pacoti", "Pacujá",
                        "Palmácia", "Paracuru", "Paraipaba", "Parambu",
                        "Paramoti", "Pedra Branca", "Penaforte", "Pentecoste",
                        "Pereiro", "Pindoretama", "Piquet Carneiro",
                        "Pires Ferreira", "Poranga", "Porteiras", "Potengi",
                        "Potiretama", "QUITERIANÓPOLIS", "Quixadá", "Quixelô",
                        "Quixeramobim", "Quixeré", "Redenção", "Reriutaba",
                        "Russas", "Saboeiro", "Santana do Acaraú",
                        "Santana do Cariri", "Santa Quitéria", "São Benedito",
                        "São Gonçalo do Amarante", "São João do Jaguaribe",
                        "São Luís do Curu", "Senador Pompeu", "Senador Sá",
                        "Sobral", "Solonópole", "Tabuleiro do Norte",
                        "Tamboril", "Tauá", "Tianguá", "Trairi", "Tururu",
                        "Ubajara", "Umari", "Umirim", "Uruburetama", "Uruoca",
                        "Varjota", "Várzea Alegre", "Viçosa do Ceará"]},
    "df": {"sigla": "DF", "nome": "Distrito Federal",
           "comarcas": ["Brasília", "Brazlândia", "Ceilândia", "Gama", "Guará",
                        "Núcleo Bandeirante", "Paranoá", "Planaltina",
                        "Recanto das Emas", "Riacho Fundo", "Samambaia",
                        "Santa Maria", "São Sebastião", "Sobradinho",
                        "Taguatinga"]},
    "es": {"sigla": "ES", "nome": "Espírito Santo",
           "comarcas": ["Afonso Claudio", "Água Doce do Norte", "Aguia Branca",
                        "Alegre", "Alfredo Chaves", "Alto Rio Novo",
                        "Anchieta", "Apiacá", "Aracruz", "Atílio Vivacqua",
                        "Baixo Guandu", "Barra de São Francisco",
                        "Boa Esperança", "Bom Jesus do Norte",
                        "Cachoeiro de Itapemirim", "Cariacica", "Castelo",
                        "Colatina", "Conceição da Barra",
                        "Conceição do Castelo", "Domingos Martins",
                        "Dores do Rio Preto", "Ecoporanga", "Ecoporonga",
                        "Fundão", "Guaçui", "Guarapari", "Ibatiba", "Ibiraçu",
                        "Ibitirama", "Iconha", "Irupi", "Itaguaçu",
                        "Itapemirim", "Itarana", "Iuna", "Jaguaré",
                        "Jerônimo Monteiro", "João Neiva", "Laranja da Terra",
                        "Linhares", "Mantenópolis", "Marataízes",
                        "Marechal Floriano", "Marilândia", "Mimoso do Sul",
                        "Montanha", "Mucurici", "Muniz Freire", "Muqui",
                        "Nova Venécia", "Pancas", "Pedro Canário", "Pinheiros",
                        "Piúma", "Presidente Kennedy", "Rio Bananal",
                        "Rio Novo do Sul", "Santa Leopoldina",
                        "Santa Maria de Jetiba", "Santa Teresa",
                        "São Domingos do Norte", "São Gabriel da Palha",
                        "São José do Calçado", "São Mateus", "Serra",
                        "Vargem Alta", "Venda Nova do Imigrante", "Viana",
                        "Vila Velha", "Vitória"]},
    "go": {"sigla": "GO", "nome": "Goiás",
           "comarcas": ["Abadiânia", "Acreúna", "Águas Lindas", "Alexânia",
                        "Alto Paraíso", "Alvorada do Norte", "Anápolis",
                        "Anicuns", "Aparecida de Goiânia", "Araçu",
                        "Aragarças", "Aruanã", "Aurilândia", "Barro Alto",
                        "Bela Vista de Goiás", "Bom Jesus", "Buriti Alegre",
                        "Cachoeira Alta", "Cachoeira Dourada", "Caçu",
                        "Caiapônia", "Caldas Novas", "Campinorte",
                        "Campos Belos", "Carmo do Rio Verde", "Catalão",
                        "Cavalcante", "Ceres", "Cidade Ocidental",
                        "Cocalzinho de Goiás", "Corumbá de Goiás",
                        "Corumbaíba", "Cristalina", "Cromínia", "Cumari",
                        "Doverlândia", "Edéia", "Estrela do Norte",
                        "Fazenda Nova", "Firminópolis", "Flores de Goiás",
                        "Formosa", "Formoso", "Goianápolis", "Goiandira",
                        "Goianésia", "Goiânia", "Goianira", "Goiás",
                        "Goiatuba", "Guapó", "Hidrolândia", "Iaciara",
                        "Inhumas", "Ipameri", "Iporá", "Israelândia",
                        "Itaberaí", "Itaguaru", "Itajá", "Itapaci",
                        "Itapirapuã", "Itapuranga", "Itauçu", "Itumbiara",
                        "Ivolândia", "Jandaia", "Jaraguá", "Jataí", "Joviânia",
                        "Jussara", "Leopoldo de Bulhões", "Luziânia",
                        "Mara Rosa", "Maurilândia", "Minaçu", "Mineiros",
                        "Montes Claros de Goiás", "Montividiu", "Morrinhos",
                        "Mossâmedes", "Mozarlândia", "Nazário", "Nerópolis",
                        "Niquelândia", "Nova Crixás", "Novo Gama", "Orizona",
                        "Padre Bernardo", "Palmeiras de Goiás", "Panamá",
                        "Paranaiguara", "Paraúna", "Petrolina de Goiás",
                        "Piracanjuba", "Piranhas", "Pirenópolis",
                        "Pires do Rio", "Planaltina", "Pontalina", "Porangatu",
                        "Posse", "Quirinópolis", "Rialma", "Rio Verde",
                        "Rubiataba", "Sanclerlândia", "Santa Cruz de Goiás",
                        "Santa Helena de Goiás", "Santa Terezinha de Goiás",
                        "Santo Antônio do Descoberto", "São Domingos",
                        "São Luís de Montes Belos", "São Miguel do Araguaia",
                        "São Simão", "Senador Canedo", "Serranópolis",
                        "Silvânia", "Taquaral de Goiás", "Trindade",
                        "Turvânia", "Uruaçu", "Uruana", "Urutaí",
                        "Valparaíso de Goiás", "Varjão", "Vianópolis"]},
    "ma": {"sigla": "MA", "nome": "Maranhão",
           "comarcas": ["Açailândia", "Alcântara", "Alto Parnaíba",
                        "Amarante do Maranhão", "Anajatuba", "Araioses",
                        "Arame", "Arari", "Bacabal", "Bacuri", "Balsas",
                        "Barão de Grajaú", "Barra do Corda", "Barreirinhas",
                        "Bequimão", "Bom Jardim", "Brejo", "Buriti",
                        "Buriti Bravo", "Buriticupu", "Cândido Mendes",
                        "Cantanhede", "Carolina", "Carutapera", "Caxias",
                        "Cedral", "Chapadinha", "Codó", "Coelho Neto",
                        "Colinas", "Coroatá", "Cururupu", "Dom Pedro",
                        "Esperantinópolis", "Estreito",
                        "Governador Eugênio Barros", "Governador Nunes Freire",
                        "Grajaú", "Guimarães", "Humberto de Campos", "Icatu",
                        "Igarapé Grande", "Ilha de São Luís", "Imperatriz",
                        "Itapecuru-Mirim", "Itinga", "João Lisboa",
                        "Joselândia", "Lago da Pedra", "Loreto",
                        "Magalhães de Almeida", "Maracaçumé", "Matinha",
                        "Matões", "Mirador", "Mirinzal", "Monção",
                        "Montes Altos", "Morros", "Olho D'Água das Cunhãs",
                        "Olinda Nova do Maranhão", "Paço do Lumiar",
                        "Paraibano", "Parnarama", "Passagem Franca",
                        "Pastos Bons", "Paulo Ramos", "Pedreiras", "Penalva",
                        "Pindaré-Mirim", "Pinheiro", "Pio XII",
                        "Poção de Pedras", "Porto Franco", "Presidente Dutra",
                        "Raposa", "Riachão", "Rosário", "Santa Helena",
                        "Santa Inês", "Santa Luzia", "Santa Luzia do Paruá",
                        "Santa Quitéria do Maranhão", "Santa Rita",
                        "Santo Antonio dos Lopes", "São Bento", "São Bernardo",
                        "São Domingos do Azeitão", "São Domingos do Maranhão",
                        "São Francisco do Maranhão", "São João Batista",
                        "São João dos Patos", "São José de Ribamar",
                        "São Luís", "São Luís Gonzaga do Maranhão",
                        "São Mateus do Maranhão", "São Pedro da Água Branca",
                        "São Raimundo das Mangabeiras", "São Vicente Ferrer",
                        "Senador La Rocque", "Sucupira do Norte",
                        "Tasso Fragoso", "Timbiras", "Timon", "Tuntum",
                        "Turiaçu", "Tutóia", "Urbano Santos", "Vargem Grande",
                        "Viana", "Vitória do Mearim", "Vitorino Freire",
                        "Zé Doca"]},
    "mg": {"sigla": "MG", "nome": "Minas Gerais",
           "comarcas": ["Abaeté", "Abre Campo", "Açucena", "Águas Formosas",
                        "Aimorés", "Aiuruoca", "Além Paraíba", "Alfenas",
                        "Almenara", "Alpinópolis", "Alto Rio Doce",
                        "Alvinópolis", "Andradas", "Andrelândia", "Araçuaí",
                        "Araguari", "Araxá", "Arcos", "Areado", "Arinos",
                        "Baependi", "Bambuí", "Barão de Cocais", "Barbacena",
                        "Barreiro", "Barroso", "Belo Horizonte", "Belo Vale",
                        "Betim", "Bicas", "Boa Esperança", "Bocaiúva",
                        "Bom Despacho", "Bom Sucesso", "Bonfim",
                        "Bonfinópolis de Minas", "Borda da Mata", "Botelhos",
                        "Brasília de Minas", "Brasópolis", "Brazópolis",
                        "Brumadinho", "Bueno Brandão", "Buenópolis", "Buritis",
                        "Cabo Verde", "Cachoeira de Minas", "Caeté", "Caldas",
                        "Camanducaia", "Cambuí", "Cambuquira", "Campanha",
                        "Campestre", "Campina Verde", "Campo Belo",
                        "Campos Altos", "Campos Gerais", "Canápolis",
                        "Candeias", "Capelinha", "Capinópolis", "Carandaí",
                        "Carangola", "Caratinga", "Carlos Chagas",
                        "Carmo da Mata", "Carmo de Minas", "Carmo do Cajuru",
                        "Carmo do Paranaíba", "Carmo do Rio Claro",
                        "Carmópolis de Minas", "Cássia", "Cataguases",
                        "Caxambu", "Cláudio", "Conceição das Alagoas",
                        "Conceição do Mato Dentro", "Conceição do Rio Verde",
                        "Congonhas", "Conquista", "Conselheiro Lafaiete",
                        "Conselheiro Pena", "Contagem", "Coração de Jesus",
                        "Corinto", "Coromandel", "Coronel Fabriciano",
                        "Cristina", "Cruzília", "Curvelo", "Diamantina",
                        "Divino", "Divinópolis", "Dores do Indaiá",
                        "Elói Mendes", "Entre Folhas", "Entre-Rios de Minas",
                        "Ervália", "Esmeraldas", "Espera Feliz", "Espinosa",
                        "Estrela do Sul", "Eugenópolis", "Extrema", "Ferros",
                        "Formiga", "Francisco Sá", "Frutal", "Galiléia",
                        "Governador Valadares", "Grão-Mogol", "Guanhães",
                        "Guapé", "Guaranésia", "Guarani", "Guaxupé", "Ibiá",
                        "Ibiraci", "Ibirité", "Igarapé", "Iguatama", "Inhapim",
                        "Ipanema", "Ipatinga", "Itabira", "Itabirito",
                        "Itaguara", "Itajubá", "Itamarandiba", "Itambacuri",
                        "Itamoji", "Itamonte", "Itanhandu", "Itanhomi",
                        "Itapagipe", "Itapajipe", "Itapecerica", "Itaúna",
                        "Ituiutaba", "Itumirim", "Iturama", "Jaboticatubas",
                        "Jacinto", "Jacuí", "Jacutinga", "Janaúba", "Januária",
                        "Jequeri", "Jequitinhonha", "João Monlevade",
                        "João Pinheiro", "Juiz de Fora", "Lagoa da Prata",
                        "Lagoa Santa", "Lajinha", "Lambari", "Lavras",
                        "Leopoldina", "Lima Duarte", "Luz", "Machado",
                        "Malacacheta", "Manga", "Manhuaçu", "Manhumirim",
                        "Mantena", "Mar de Espanha", "Mariana",
                        "Martinho Campos", "Mateus Leme", "Matias Barbosa",
                        "Matozinhos", "Medina", "Mercês", "Mesquita",
                        "Minas Novas", "Miradouro", "Miraí", "Montalvânia",
                        "Monte Alegre de Minas", "Monte Azul", "Monte Belo",
                        "Monte Carmelo", "Monte Santo de Minas",
                        "Montes Claros", "Monte Sião", "Morada Nova de Minas",
                        "Muriaé", "Mutum", "Muzambinho", "Nanuque", "Natércia",
                        "Nepomuceno", "Nova Era", "Nova Lima", "Nova Ponte",
                        "Nova Resende", "Nova Serrana", "Novo Cruzeiro",
                        "Oliveira", "Ouro Branco", "Ouro Fino", "Ouro Preto",
                        "Palma", "Paracatu", "Pará de Minas", "Paraguaçu",
                        "Paraisópolis", "Paraopeba", "Passa-Quatro",
                        "Passa-Tempo", "Passos", "Patos de Minas",
                        "Patrocínio", "Peçanha", "Pedra Azul", "Pedralva",
                        "Pedro Leopoldo", "Perdizes", "Perdões",
                        "Piedade de Caratinga", "Piranga", "Pirapetinga",
                        "Pirapora", "Pitangui", "Piumhi", "Poço Fundo",
                        "Poços de Caldas", "Pompéu", "Ponte Nova",
                        "Ponto Chique", "Porteirinha", "Pouso Alegre",
                        "Prados", "Prata", "Pratápolis", "Presidente Olegário",
                        "Raul Soares", "Resende Costa", "Resplendor",
                        "Ribeirão das Neves", "Rio Casca", "Rio Novo",
                        "Rio Paranaíba", "Rio Pardo de Minas",
                        "Rio Piracicaba", "Rio Pomba", "Rio Preto",
                        "Rio Vermelho", "Sabará", "Sabinópolis", "Sacramento",
                        "Salinas", "Santa Bárbara", "Santa Luzia",
                        "Santa Maria do Suaçuí", "Santa Rita de Caldas",
                        "Santa Rita do Sapucaí", "Santa Vitória",
                        "Santo Antônio do Monte", "Santos Dumont",
                        "São Domingos do Prata", "São Francisco",
                        "São Gonçalo do Sapucaí", "São Gotardo",
                        "São João da Ponte", "São João Del-Rei",
                        "São João do Paraíso", "São João Evangelista",
                        "São João Nepomuceno", "São Joaquim de Bicas",
                        "São Lourenço", "São Romão", "São Roque de Minas",
                        "São Sebastião do Paraíso", "Senador Firmino", "Serro",
                        "Sete Lagoas", "Silvianópolis", "Taiobeiras",
                        "Tarumirim", "Teixeiras", "Teófilo Otôni", "Timóteo",
                        "Tiros", "Tombos", "Três Corações", "Três Marias",
                        "Três Pontas", "Tupaciguara", "Turmalina", "Ubá",
                        "Uberaba", "Uberlândia", "Unaí", "Vargem Alegre",
                        "Varginha", "Várzea da Palma", "Vazante", "Vespasiano",
                        "Viçosa", "Virginópolis", "Visconde do Rio Branco"]},
    "ms": {"sigla": "MS", "nome": "Mato Grosso do Sul",
           "comarcas": ["Água Clara", "Amambaí", "Anastácio", "Anaurilândia",
                        "Angélica", "Aparecida do Taboado", "Aquidauana",
                        "Bandeirantes", "Bataguassu", "Batayporã",
                        "Bela Vista", "Bonito", "Brasilândia", "Caarapó",
                        "Camapuã", "Campo Grande", "Cassilândia",
                        "Chapadão do Sul", "CORONEL SAPUCAIA", "Corumbá",
                        "Costa Rica", "Coxim", "Deodápolis",
                        "Dois Irmãos do Buriti", "Dourados", "Eldorado",
                        "Fátima do Sul", "Glória de Dourados", "Iguatemi",
                        "Inocência", "Itaporã", "Itaquiraí", "Ivinhema",
                        "Jardim", "Maracajú", "Miranda", "Mundo Novo",
                        "Naviraí", "Nioaque", "Nova Alvorada do Sul",
                        "Nova Andradina", "Paranaíba", "Pedro Gomes",
                        "Ponta Porã", "Porto Murtinho", "Ribas do Rio Pardo",
                        "Rio Brilhante", "Rio Negro",
                        "Rio Verde de Mato Grosso", "São Gabriel do Oeste",
                        "Sete Quedas", "Sidrolândia", "Sonora", "Terenos"]},
    "mt": {"sigla": "MT", "nome": "Mato Grosso",
           "comarcas": ["Água Boa", "Alta Floresta", "Alto Araguaia",
                        "Alto Garças", "Alto Taquari", "Apiacás", "Araputanga",
                        "Arenápolis", "Aripuanã", "Barra do Bugres",
                        "Barra do Garças", "Brasnorte", "Cáceres",
                        "Campinápolis", "Campo Novo do Parecis", "Campo Verde",
                        "Canarana", "Chapada dos Guimarães", "Cláudia",
                        "Colíder", "Colniza", "Comodoro", "Cotriguaçu",
                        "Cuiabá", "Diamantino", "Dom Aquino", "Feliz Natal",
                        "Guarantã do Norte", "Guiratinga", "Itaúba",
                        "Itiquira", "Jaciara", "Jauru", "Juara", "Juína",
                        "Juscimeira", "Lucas do Rio Verde", "Marcelândia",
                        "Matupá", "Mirassol d'Oeste", "Nobres", "Nortelândia",
                        "Nova Canaã do Norte", "Nova Monte Verde",
                        "Nova Mutum", "Nova Ubiratã", "Nova Xavantina",
                        "Novo São Joaquim", "Paranaíta", "Paranatinga",
                        "Pedra Preta", "Peixoto de Azevedo", "Poconé",
                        "Pontes e Lacerda", "Porto Alegre do Norte",
                        "Porto dos Gaúchos", "Porto Esperidião", "Poxoréo",
                        "Poxoréu", "Primavera do Leste", "Querência",
                        "Ribeirão Cascalheira", "Rio Branco", "Rondonópolis",
                        "Rosário Oeste", "Santo Antônio de Leverger",
                        "São Félix do Araguaia", "São José do Rio Claro",
                        "São José dos Quatro Marcos", "Sapezal", "Sinop",
                        "Sorriso", "Tabaporã", "Tangará da Serra", "Tapurah",
                        "Terra Nova do Norte", "Várzea Grande", "Vera",
                        "Vila Bela da Santíssima Trindade", "Vila Rica"]},
    "pa": {"sigla": "PA", "nome": "Pará",
           "comarcas": ["Abaetetuba", "Abel Figueiredo", "Acará", "Afuá",
                        "Água Azul do Norte", "Alenquer", "Almeirim",
                        "Altamira", "Anajás", "Ananindeua", "Anapu",
                        "Araguaia", "Augusto Corrêa", "Aurora do Pará",
                        "Aveiro", "Bagre", "Baião", "Bannach", "Barcarena",
                        "Belém", "Belterra", "Benevides",
                        "Bom Jesus do Tocantis", "Bonito", "Bragança",
                        "Brasil Novo", "Brejo Grande do Araguaia",
                        "Breu Branco", "Breves", "Bujaru",
                        "Cachoeira do Arari", "Cachoeira do Piriá", "Cametá",
                        "Canaã dos Carajás", "Capanema", "Capitão Poço",
                        "Castanhal", "Chaves", "Colares",
                        "Conceição do Araguaia", "Concórdia do Pará",
                        "Cumaru do Norte", "Curionópolis", "Curralinho",
                        "Curuá", "Curuçá", "Dom Eliseu",
                        "Eldorado dos Carajás", "Faro", "Floresta do Araguaia",
                        "Garrafão do Norte", "Goianésia do Pará", "Gurupá",
                        "Icoaraci", "Igarapé-Açu", "Igarapé-Miri", "Inhangapi",
                        "Ipixuna", "Ipixuna do Pará", "Irituia", "Itaituba",
                        "Itupiranga", "Jacarecanga", "Jacundá", "Juruti",
                        "Limoeiro do Ajuru", "Mãe do Rio", "Magalhães Barata",
                        "Marabá", "Maracanã", "Marapanim", "Marituba",
                        "Medicilândia", "Melgaço", "Mocajuba", "Moju",
                        "Monte Alegre", "Mosqueiro", "Muaná",
                        "Nova Esperança do Piriá", "Nova Timboteua",
                        "Novo Progresso", "Novo Repartimento", "Óbidos",
                        "Oeiras do Pará", "Oriximina", "Ourém",
                        "Ourilândia do Norte", "Pacajá", "Palestina do Pará",
                        "Paragominas", "Parauapebas", "Pau d'Arco",
                        "Peixe-Boi", "Piçarra", "Placas", "Ponta de Pedras",
                        "Portel", "Porto de Moz", "Prainha", "Primavera",
                        "Quatipuru", "Redenção", "Rio Maria", "Rondon do Pará",
                        "Rurópolis", "Salinópolis", "Salvaterra",
                        "Santa Bárbara do Pará", "Santa Cruz do Arari",
                        "Santa Isabel do Pará", "Santa Izabel do Pará",
                        "Santa Luzia do Pará", "Santa Maria das Barreiras",
                        "Santa Maria do Pará", "Santana do Araguaia",
                        "Santarém", "Santarém Novo", "Santo Antônio do Tauá",
                        "São Caetano de Odivelas", "São Domingos do Araguaia",
                        "São Domingos do Capim", "São Félix do Xingu",
                        "São Francisco do Pará", "São Geraldo do Araguaia",
                        "São João da Ponta", "São João de Pirabas",
                        "São João do Araguaia", "São Miguel do Guamá",
                        "São Sebastião da Boa Vista", "Sapucaia",
                        "Senador José Porfírio", "Soure", "Tacumã",
                        "Tailândia", "Terra Alta", "Terra Santa", "Tomé-Açu",
                        "Tracuateua", "Trairão", "Tucumã", "Tucuruí",
                        "Ulianópolis", "Uruará", "Vigia", "Viseu",
                        "Vitória do Xingu", "Xinguara"]},
    "pb": {"sigla": "PB", "nome": "Paraíba",
           "comarcas": ["Água Branca", "Alagoa Grande", "Alagoa Nova",
                        "Alagoinha", "Alhandra", "Araçagi", "Arara", "Araruna",
                        "Areia", "Aroeiras", "Bananeiras",
                        "Barra de Santa Rosa", "Bayeux", "Belém",
                        "Bonito de Santa Fé", "Boqueirão", "Brejo do Cruz",
                        "Caapora", "Cabaceiras", "Cabedelo",
                        "Cacimba de Dentro", "Caicara", "Cajazeiras",
                        "Campina Grande", "Catole do Rocha", "Catolé do Rocha",
                        "Conceição", "Conde", "Coremas",
                        "Cruz do Espirito Santo", "Cuite", "Esperança",
                        "Guarabira", "Gurinhem", "Inga", "Itabaiana",
                        "Itaporanga", "Jacarau", "João Pessoa", "Juazeirinho",
                        "Lucena", "Malta", "Mamanguape", "Mari", "Monteiro",
                        "Patos", "Paulista", "Pedras de Fogo", "Pianco",
                        "Picui", "Pilar", "Pilões", "Pirpirituba", "Pocinhos",
                        "Pombal", "Prata", "Princesa Isabel", "Queimadas",
                        "Remigio", "Rio Tinto", "Santa Luzia",
                        "Santana dos Garrotes", "Santa Rita", "São Bento",
                        "São João do Cariri", "São João do Rio do Peixe",
                        "São José de Piranhas", "São Mamede", "Sape", "Sapé",
                        "Serra Branca", "Serraria", "Solanea", "Solânea",
                        "Soledade", "Sousa", "Sume", "Taperoa", "Teixeira",
                        "Uirauna", "Umbuzeiro"]},
    "pe": {"sigla": "PE", "nome": "Pernambuco",
           "comarcas": ["Abreu e Lima", "Afogados da Ingazeira", "Afrânio",
                        "Agrestina", "Água Preta", "Águas Belas", "Alagoinha",
                        "Aliança", "Altinho", "Amaraji", "Angelim",
                        "Araripina", "Arcoverde", "Barreiros",
                        "Belém de Maria", "Belém do São Francisco",
                        "Belo Jardim", "Betânia", "Bezerros", "Bodocó",
                        "Bom Conselho", "Bom Jardim", "Bonito", "Brejão",
                        "Brejo da Madre de Deus", "Buenos Aires", "Buíque",
                        "Cabo", "Cabo de Santo Agostinho", "Cabrobó",
                        "Cachoeirinha", "Caetés", "Calçado", "Camaragibe",
                        "Camocim de São Félix", "Canhotinho", "Capoeiras",
                        "Carnaíba", "Carpina", "Caruaru", "Catende",
                        "Chã Grande", "Condado", "Correntes", "Cortês",
                        "Cumaru", "Cupira", "Custódia", "Escada", "Exu",
                        "Feira Nova", "Fernando de Noronha", "Ferreiros",
                        "Flores", "Floresta", "Gameleira", "Garanhuns",
                        "Glória de Goitá", "Glória do Goitá", "Goiana",
                        "Gravatá", "Iati", "Ibimirim", "Ibirajuba", "Igarassú",
                        "Inajá", "Ipojuca", "Ipubi", "Itaíba", "Itamaracá",
                        "Itambé", "Itapetim", "Itapissuma", "Itaquitinga",
                        "Jaboatão dos Guararapes", "Jataúba", "João Alfredo",
                        "Joaquim Nabuco", "Jupi", "Jurema", "Lagoa do Carro",
                        "Lagoa do Itaenga", "Lagoa do Ouro", "Lagoa dos Gatos",
                        "Lagoa Grande", "Lajedo", "Limoeiro", "Macaparana",
                        "Maraial", "Mirandiba", "Moreilândia", "Moreno",
                        "Nazaré da Mata", "Olinda", "Orobó", "Orocó",
                        "Ouricuri", "Palmares", "Palmeirina", "Panelas",
                        "Parnamirim", "Passira", "Paudalho", "Paulista",
                        "Pedra", "Pesqueira", "Petrolândia", "Petrolina",
                        "Poção", "Pombos", "Primavera", "Quipapá", "Recife",
                        "Riacho das Almas", "Ribeirão", "Rio Formoso", "Sairé",
                        "Salgueiro", "Saloá", "Sanharó",
                        "Santa Cruz do Capibaribe", "Santa Maria da Boa Vista",
                        "Santa Maria do Cambucá", "São Benedito do Sul",
                        "São Bento do Una", "São Caetano", "São João",
                        "São Joaquim do Monte", "São José da Coroa Grande",
                        "São José do Belmonte", "São José do Egito",
                        "São Lourenço da Mata", "São Vicente Ferrer",
                        "Serra Talhada", "Serrita", "Sertânia", "Sirinhaém",
                        "Solidão", "Surubim", "Tabira", "Tacaimbó", "Tacaratu",
                        "Tamandaré", "Taquaritinga do Norte", "Terra Nova",
                        "Timbaúba", "Toritama", "Tracunhaém", "Trindade",
                        "Triunfo", "Tuparetama", "Venturosa", "Verdejante",
                        "Vertentes", "Vicência", "Vitória de Santo Antão"]},
    "pi": {"sigla": "PI", "nome": "Piauí",
           "comarcas": ["Água Branca", "Alto Longá", "Altos", "Amarante",
                        "Angical do Piauí", "Anísio de Abreu",
                        "Antônio Almeida", "Aroazes", "Arraial do Piauí",
                        "Avelino Lopes", "Barras", "Barro Duro", "Batalha",
                        "Beneditinos", "Bertolínea", "Bocaina", "Bom Jesus",
                        "Buriti dos Lopes", "Campinas do Piauí", "Campo Maior",
                        "Canto do Buriti", "Capitão de Campos", "Caracol",
                        "Castelo do Piauí", "Cocal", "Conceição do Canindé",
                        "Corrente", "Cristalândia do Piauí", "Cristino Castro",
                        "Curimatá", "Demerval Lobão", "Elesbão Veloso",
                        "Eliseu Martins", "Esperantina", "Floriano",
                        "Francinópolis", "Francisco Santos", "Fronteiras",
                        "Gilbués", "Guadalupe", "Inhuma", "Ipiranga do Piauí",
                        "Isaias Coelho", "Itainópolis", "Itaueira", "Jaicós",
                        "Jerumenha", "Joaquim Pires", "José de Freitas",
                        "Landri Sales", "Luís Correia", "Luzilândia",
                        "Manoel Emídio", "Marcolândia", "Marcos Parente",
                        "Matias Olímpio", "Miguel Alves", "Monsenhor Gil",
                        "Monte Alegre do Piauí", "Nazaré do Piauí",
                        "Nossa Senhora dos Remédios", "Oeiras", "Padre Marcos",
                        "Paes Landim", "Palmeirais", "Parnaguá", "Parnaíba",
                        "Paulistana", "Pedro II", "Picos", "Pimenteiras",
                        "Pio IX", "Piracuruca", "Piripiri", "Porto",
                        "Redenção do Gurgueia", "Regeneração",
                        "Ribeiro Gonçalves", "Santa Cruz do Piauí",
                        "Santa Filomena", "São Félix do Piauí",
                        "São Gonçalo do Piauí", "São João do Piauí",
                        "São Miguel do Tapuio", "São Pedro do Piauí",
                        "São Raimundo Nonato", "Simões", "Simplício Mendes",
                        "Socorro do Piauí", "Teresina", "União", "Uruçuí",
                        "Valença do Piauí", "Várzea Grande"]},
    "pr": {"sigla": "PR", "nome": "Paraná",
           "comarcas": ["Almirante Tamandaré", "Altônia", "Alto Paraná",
                        "Alto Piquiri", "Ampére", "Andirá", "Antonina",
                        "Apucarana", "Arapongas", "Arapoti", "Araucária",
                        "Assaí", "Assis Chateaubriand", "Astorga",
                        "Bandeirantes", "Barbosa Ferraz", "Barracão",
                        "Bela Vista do Paraíso", "Bocaiúva do Sul", "Cambará",
                        "Cambé", "Campina da Lagoa", "Campina Grande do Sul",
                        "Campo Largo", "Campo Mourão", "Cândido de Abreu",
                        "Cantagalo", "Capanema", "Capitão Leônidas Marques",
                        "Carambeí", "Cariúva", "Carlópolis", "Cascavel",
                        "Castro", "Catanduvas", "Centenário do Sul",
                        "Cerro Azul", "Chopinzinho", "Cianorte",
                        "Cidade Gaúcha", "Clevelândia", "Colombo", "Colorado",
                        "Congonhinhas", "Corbélia", "Cornélio Procópio",
                        "Coronel Vivida", "Cruzeiro do Oeste", "Curitiba",
                        "Curiúva", "Dois Vizinhos", "Engenheiro Beltrão",
                        "Faxinal", "Fazenda Rio Grande", "Formosa do Oeste",
                        "Foz do Iguaçu", "Francisco Beltrão", "Goioerê",
                        "Grandes Rios", "Guáira", "Guaraniaçu", "Guarapuava",
                        "Guaratuba", "Ibaiti", "Ibiporã", "Icaraíma",
                        "Imbituva", "Ipiranga", "Iporã", "Irati", "Iretama",
                        "Ivaiporã", "Jacarezinho", "Jaguapitã", "Jaguariaíva",
                        "Jandaia do Sul", "Joaquim Távora", "Lapa",
                        "Laranjeiras do Sul", "Loanda", "Londrina", "Mallet",
                        "Mamborê", "Mandaguaçu", "Mandaguari", "Mangueirinha",
                        "Manoel Ribas", "Marechal Cândido Rondon", "Marialva",
                        "Marilândia do Sul", "Maringá", "Marmeleiro",
                        "Matelândia", "Matinhos", "Medianeira", "Morretes",
                        "Nova Aurora", "Nova Esperança", "Nova Fátima",
                        "Nova Londrina", "Ortigueira", "Palmas", "Palmeira",
                        "Palmital", "Palotina", "Paraíso do Norte",
                        "Paranacity", "Paranaguá", "Paranavaí", "Pato Branco",
                        "Peabiru", "Pérola", "Pinhais", "Pinhalzinho",
                        "Pinhão", "Piraí do Sul", "Piraquara", "Pitanga",
                        "Ponta Grossa", "Pontal do Paraná", "Porecatu",
                        "Primeiro de Maio", "Prudentópolis",
                        "Quedas do Iguaçu", "Realeza", "Rebouças", "Reserva",
                        "Ribeirão Claro", "Ribeirão do Pinhal",
                        "Rio Branco do Sul", "Rio Negro", "Rolândia",
                        "Salto do Lontra", "Santa Fé", "Santa Felicidade",
                        "Santa Helena", "Santa Isabel do Ivaí",
                        "Santa Mariana", "Santo Antônio da Platina",
                        "Santo Antônio do Sudoeste", "São Jerônimo da Serra",
                        "São João", "São João do Ivaí", "São João do Triunfo",
                        "São José dos Pinhais", "São Mateus do Sul",
                        "São Miguel do Iguaçu", "Sarandi", "Sengés",
                        "Sertanópolis", "Siqueira Campos", "Sítio Cercado",
                        "Teixeira Soares", "Telêmaco Borba", "Terra Boa",
                        "Terra Rica", "Terra Roxa", "Tibagi", "Toledo",
                        "Tomazina", "Ubiratã", "Umuarama", "União da Vitória",
                        "Uraí", "Wenceslau Braz"]},
    "rj": {"sigla": "RJ", "nome": "Rio de Janeiro",
           "comarcas": ["Alcântara", "Angra dos Reis", "Aperibe", "Araruama",
                        "Areal", "Arraial do Cabo", "Barra do Piraí",
                        "Barra Mansa", "Belford Roxo", "Bom Jardim",
                        "Bom Jesus de Itabapoana", "Búzios", "Cabo Frio",
                        "Cachoeiras de Macacu", "Cambuci",
                        "Campos dos Goytacazes", "Cantagalo",
                        "Carapebus / Quissamã", "Cardoso Moreira", "Carmo",
                        "Casimiro de Abreu", "Caxias", "Conceição de Macabu",
                        "Cordeiro", "Cordeiro-Macuco", "Duas Barras",
                        "Duque de Caxias", "Engenheiro Paulo de Frontin",
                        "Guadalupe", "Guapimirim", "Iguaba Grande",
                        "Ilha do Governador", "Inhaúma", "Inhomirim",
                        "Itaboraí", "Itaguaí", "Itaipava", "Italva",
                        "Itaocara", "Itaperuna", "Itatiaia", "Japeri",
                        "Laje do Muriaé", "Macaé", "Magé", "Mangaratiba",
                        "Manilha", "Maricá", "Mendes", "Mesquita",
                        "Miguel Pereira", "Miracema", "Natividade",
                        "Nilópolis", "Niterói", "Nova Friburgo", "Nova Iguaçu",
                        "Paracambi", "Paraíba do Sul", "Paraty",
                        "Paty do Alferes", "Pendotiba", "Petrópolis",
                        "Pinheiral", "Piraí", "Porciúncula", "Porto Real",
                        "Porto Real / Quatis", "Queimados", "Região Oceânica",
                        "Resende", "Rio Bonito", "Rio Claro", "Rio das Flores",
                        "Rio das Ostras", "Rio de Janeiro",
                        "Santa Maria Madalena", "Santo Antônio de Pádua",
                        "São Fidelis", "São Francisco de Itabapoana",
                        "São Gonçalo", "São João da Barra",
                        "São João de Meriti", "São José de Ubá",
                        "São José do Vale do Rio Preto", "São Pedro da Aldeia",
                        "São Sebastião do Alto", "Sapucaia", "Saquarema",
                        "Seropédica", "Silva Jardim", "Sumidouro", "Tanguá",
                        "Taquara", "Teresópolis", "Trajano de Moraes",
                        "Três Rios", "Três Rios-Areal-Levy Gasparian",
                        "Valença", "Varre-Sai", "Vassouras", "Vila Inhomirim",
                        "Volta Redonda"]},
    "rn": {"sigla": "RN", "nome": "Rio Grande do Norte",
           "comarcas": ["Acari", "Açu", "Afonso Bezerra", "Alexandria",
                        "Almino Afonso", "Angicos", "Apodi", "Areia Branca",
                        "Arês", "Assu", "Baraúna", "Caicó", "Campo Grande",
                        "Canguaretama", "Caraúbas", "Ceará Mirim", "Cruzeta",
                        "Currais Novos", "Extremoz", "Florânia", "Goianinha",
                        "Governador Dix-Sept Rosado", "Ipanguaçu", "Janduís",
                        "Jardim de Piranhas", "Jardim do Seridó",
                        "João Câmara", "Jucurutu", "Lajes", "Luís Gomes",
                        "Macaíba", "Macau", "Marcelino Vieira", "Martins",
                        "Monte Alegre", "Mossoró", "Natal", "Nísia Floresta",
                        "Nova Cruz", "Parelhas", "Parnamirim", "Patu",
                        "Pau de Ferros", "Pau dos Ferros", "Pedro Avelino",
                        "Pedro Velho", "Pendências", "Poço Branco",
                        "Portalegre", "Santa Cruz", "Santana do Matos",
                        "Santo Antônio", "São Bento do Norte",
                        "São Gonçalo do Amarante", "São João do Sabugi",
                        "São José de Mipibu", "São José do Campestre",
                        "São Miguel", "São Paulo do Potengi", "São Rafael",
                        "São Tomé", "Serra Negra do Norte", "Taipu", "Tangará",
                        "Touros", "Umarizal", "Upanema"]},
    "ro": {"sigla": "RO", "nome": "Rondônia",
           "comarcas": ["Alta Floresta d'Oeste", "Alvorada d'Oeste",
                        "Alvorada do Oeste", "Ariquemes", "Buritis", "Cacoal",
                        "Cerejeiras", "Colorado do Oeste", "Costa Marques",
                        "Espigão d'Oeste", "Guajará-Mirim", "Jaru",
                        "Ji-Paraná", "Machadinho d'Oeste", "Mirante da Serra",
                        "Nova Brasilândia d'Oeste", "Nova Mamoré",
                        "Ouro Preto do Oeste", "Pimenta Bueno", "Porto Velho",
                        "Presidente Médici", "Rolim de Moura",
                        "Santa Luzia d'Oeste", "São Francisco do Guaporé",
                        "São Miguel do Guaporé", "Vilhena"]},
    "rr": {"sigla": "RR", "nome": "Roraima",
           "comarcas": ["Alto Alegre", "Boa Vista", "Bonfim", "Cantá",
                        "Caracaraí", "Mucajaí", "Pacaraima", "Rorainópolis",
                        "São Luiz do Anauá"]},
    "rs": {"sigla": "RS", "nome": "Rio Grande do Sul",
           "comarcas": ["Agudo", "Alegrete", "Alvorada", "Antônio Prado",
                        "Arroio do Meio", "Arroio dos Ratos",
                        "Arroio do Tigre", "Arroio Grande", "Arvorezinha",
                        "Augusto Pestana", "Bagé", "Barra do Ribeiro",
                        "Bento Gonçalves", "Bom Jesus", "Butiá",
                        "Caçapava do Sul", "Cacequi", "Cachoeira do Sul",
                        "Cachoeirinha", "Camaquã", "Campina das Missões",
                        "Campo Bom", "Campo Novo", "Candelária", "Canela",
                        "Canguçu", "Canoas", "Capão da Canoa", "Carazinho",
                        "Carlos Barbosa", "Casca", "Catuípe", "Caxias do Sul",
                        "Cerro Largo", "Charqueadas", "Constantina",
                        "Coronel Bicaco", "Crissiumal", "Cruz Alta",
                        "Dois Irmãos", "Dom Pedrito", "Eldorado do Sul",
                        "Encantado", "Encruzilhada do Sul", "Erechim",
                        "Espumoso", "Estância Velha", "Esteio", "Estrela",
                        "Farroupilha", "Faxinal do Soturno", "Feliz",
                        "Flores da Cunha", "Frederico Westphalen", "Garibaldi",
                        "Gaurama", "General Câmara", "Getúlio Vargas", "Giruá",
                        "Gramado", "Gravataí", "Guaíba", "Guaporé",
                        "Guarani das Missões", "Herval", "Horizontina",
                        "Ibirubá", "Igrejinha", "Ijuí", "Iraí", "Itaqui",
                        "Ivoti", "Jaguarão", "Jaguari", "Júlio de Castilhos",
                        "Lagoa Vermelha", "Lajeado", "Lavras do Sul", "Marau",
                        "Marcelino Ramos", "Montenegro", "Mostardas",
                        "Não-Me-Toque", "Nonoai", "Nova Petrópolis",
                        "Nova Prata", "Novo Hamburgo", "Osório",
                        "Palmares do Sul", "Palmeira das Missões", "Panambi",
                        "Parobé", "Passo Fundo", "Pedro Osório", "Pelotas",
                        "Pinheiro Machado", "Piratini", "Planalto", "Portão",
                        "Porto Alegre", "Porto Xavier", "Quaraí",
                        "Restinga Seca", "Rio Grande", "Rio Pardo",
                        "Rodeio Bonito", "Ronda Alta", "Rosário do Sul",
                        "Salto do Jacuí", "Sananduva", "Santa Bárbara do Sul",
                        "Santa Cruz do Sul", "Santa Maria",
                        "Santana do Livramento", "Santa Rosa",
                        "Santa Vitória do Palmar", "Santiago", "Santo Ângelo",
                        "Santo Antônio da Patrulha",
                        "Santo Antônio das Missões", "Santo Augusto",
                        "Santo Cristo", "São Borja", "São Francisco de Assis",
                        "São Francisco de Paula", "São Gabriel",
                        "São Jerônimo", "São José do Norte",
                        "São José do Ouro", "São Leopoldo",
                        "São Lourenço do Sul", "São Luiz Gonzaga",
                        "São Marcos", "São Pedro do Sul",
                        "São Sebastião do Caí", "São Sepé", "São Valentim",
                        "São Vicente do Sul", "Sapiranga", "Sapucaia do Sul",
                        "Sarandi", "Seberi", "Sobradinho", "Soledade",
                        "Tapejara", "Tapera", "Tapes", "Taquara", "Taquari",
                        "Tenente Portela", "Terra de Areia", "Teutônia",
                        "Torres", "Tramandaí", "Três Coroas", "Três de Maio",
                        "Três Passos", "Triunfo", "Tucunduva", "Tupanciretã",
                        "Uruguaiana", "Vacaria", "Venâncio Aires", "Vera Cruz",
                        "Veranópolis", "Viamão"]},
    "sc": {"sigla": "SC", "nome": "Santa Catarina",
           "comarcas": ["Abelardo Luz", "Anchieta", "Anita Garibaldi",
                        "Araquari", "Araranguá", "Armazém", "Ascurra",
                        "Balneário Camboriú", "Balneário Piçarras",
                        "Barra Velha", "Biguaçu", "Blumenau", "Bom Retiro",
                        "Braco do Norte", "Brusque", "Caçador", "Camboriú",
                        "Campo Belo do Sul", "Campo Erê", "Campos Novos",
                        "Canoinhas", "Capinzal", "Capivari de Baixo",
                        "Catanduvas", "Chapecó", "Concórdia",
                        "Coronel Freitas", "Correia Pinto", "Criciúma",
                        "Cunha Porã", "Curitibanos", "Descanso",
                        "Dionísio Cerqueira", "Florianópolis", "Forquilhinha",
                        "Fraiburgo", "Garopaba", "Garuva", "Gaspar",
                        "Guaramirim", "HERVAL DO OESTE", "Ibirama", "Içara",
                        "Imaruí", "Imbituba", "Indaial", "Ipumirim", "Itá",
                        "Itaiópolis", "Itajaí", "Itapema", "Itapiranga",
                        "Itapoá", "Ituporanga", "Jaguaruna", "Jaraguá do Sul",
                        "Joaçaba", "Joinville", "Lages", "Laguna",
                        "Lauro Müller", "Lebon Régis", "Mafra", "Maravilha",
                        "Meleiro", "Modelo", "Mondai", "Navegantes", "Orleans",
                        "Otacílio Costa", "Palhoça", "Palmitos", "Papanduva",
                        "Pinhalzinho", "Pomerode", "Ponte Serrada",
                        "Porto Belo", "Porto União", "Presidente Getúlio",
                        "Quilombo", "Rio do Campo", "Rio do Oeste",
                        "Rio do Sul", "Rio Negrinho", "Santa Cecília",
                        "Santa Rosa do Sul", "Santo Amaro da Imperatriz",
                        "São Bento do Sul", "São Carlos", "São Domingos",
                        "São Francisco do Sul", "São João Batista",
                        "São Joaquim", "São José", "São José do Cedro",
                        "São Lourenço do Oeste", "São Miguel do Oeste",
                        "Seara", "Sombrio", "Taió", "Tangará", "Tijucas",
                        "Timbó", "Trombudo Central", "Tubarão", "Turvo",
                        "Urubici", "Urussanga", "Videira", "Xanxerê",
                        "Xaxim"]},
    "se": {"sigla": "SE", "nome": "Sergipe",
           "comarcas": ["Aquidabã", "Aracaju", "Arauá", "Barra dos Coqueiros",
                        "Boquim", "Campo do Brito", "Canindé", "Capela",
                        "Carira", "Carmópolis", "Cedro", "Cristinápolis",
                        "Estância", "Frei Paulo", "Gararu", "Indiaroba",
                        "Itabaiana", "Itabaianinha", "Itaporanga D'Ajuda",
                        "Japaratuba", "Lagarto", "Laranjeiras", "Malhador",
                        "Maruim", "Maurim", "Neópolis",
                        "Nossa Senhora da Glória", "Nossa Senhora das Dores",
                        "Nossa Senhora do Socorro", "Pacatuba", "Poço Redondo",
                        "Poço Verde", "Porto da Folha", "Propriá",
                        "Riachão do Dantas", "Riachuelo", "Ribeirópolis",
                        "São Cristóvão", "Simão Dias", "Tobias Barreto",
                        "Umbaúba"]},
    "sp": {"sigla": "SP", "nome": "São Paulo",
           "comarcas": ["Adamantina", "Aguaí", "Águas de Lindóia", "Agudos",
                        "Altinópolis", "Americana", "Américo Brasiliense",
                        "Amparo", "Andradina", "Angatuba", "Aparecida",
                        "Apiaí", "Araçatuba", "Araraquara", "Araras",
                        "Artur Nogueira", "Arujá", "Assis", "Atibaia",
                        "Auriflama", "Avaré", "Bananal", "Bariri",
                        "Barra Bonita", "Barretos", "Barueri", "Bastos",
                        "Batatais", "Bauru", "Bebedouro", "Bertioga", "Bilac",
                        "Birigui", "Boituva", "Borborema", "Botucatu",
                        "Bragança Paulista", "Brodowski", "Brotas", "Buri",
                        "Buritama", "Cabreúva", "Caçapava",
                        "Cachoeira Paulista", "Caconde", "Cafelândia",
                        "Caieiras", "Cajamar", "Cajuru", "Campinas",
                        "Campo Limpo Paulista", "Campos do Jordão", "Cananéia",
                        "Cândido Mota", "Capão Bonito", "Capivari",
                        "Caraguatatuba", "Carapicuiba", "Cardoso",
                        "Casa Branca", "Catanduva", "Cedral",
                        "Cerqueira Cesar", "Cerquilho", "Chavantes", "Colina",
                        "Conchal", "Conchas", "Cordeirópolis", "Cosmópolis",
                        "Cotia", "Cravinhos", "Cruzeiro", "Cubatão", "Cunha",
                        "Descalvado", "Diadema", "Dois Córregos", "Dracena",
                        "Duartina", "Eldorado", "Embu das Artes", "Embu-Guaçu",
                        "Espírito Santo do Pinhal", "Estrela D’Oeste",
                        "Fartura", "Fernandópolis", "Ferraz de Vasconcelos",
                        "Flórida Paulista", "Franca", "Francisco Morato",
                        "Franco da Rocha", "Gália", "Garça", "General Salgado",
                        "Getulina", "Guaianazes", "Guaíra", "Guará",
                        "Guararapes", "Guararema", "Guaratinguetá", "Guariba",
                        "Guarujá", "Guarulhos", "Holambra", "Hortolândia",
                        "Iacanga", "Ibaté", "Ibitinga", "Ibiúna", "Iepê",
                        "Igarapava", "Iguape", "Ilhabela", "Ilha Bela",
                        "Ilha Solteira", "Indaiatuba", "Ipaussu", "Ipiranga",
                        "Ipuã", "Itaberá", "Itaí", "Itajobi", "Itanhaém",
                        "Itapecerica da Serra", "Itapetininga", "Itapeva",
                        "Itapevi", "Itapira", "Itápolis", "Itaporanga",
                        "Itaquaquecetuba", "Itaquera", "Itararé", "Itariri",
                        "Itatiaia", "Itatiba", "Itatinga", "Itirapina", "Itu",
                        "Itupeva", "Ituverava", "Jabaquara", "Jaboticabal",
                        "Jacareí", "Jacupiranga", "Jaguariúna", "Jales",
                        "Jandira", "Jardinópolis", "Jarinu", "Jaú",
                        "José Bonifácio", "Jundiaí", "Junqueirópolis",
                        "Juquiá", "Lapa", "Laranjal Paulista", "Leme",
                        "Lençóis Paulista", "Limeira", "Lins", "Lorena",
                        "Louveira", "Lucélia", "Macatuba", "Macaubal",
                        "Mairinque", "Mairiporã", "Maracaí", "Marília",
                        "Martinópolis", "Matão", "Mauá", "Miguelópolis",
                        "Miracatu", "Mirandópolis", "Mirante do Paranapanema",
                        "Mirassol", "Mococa", "Mogi das Cruzes", "Mogi Guaçu",
                        "Mogi Mirim", "Mongaguá", "Monte Alegre do Sul",
                        "Monte Alto", "Monte Aprazível", "Monte Azul Paulista",
                        "Monte Mor", "Morro Agudo", "Nazaré Paulista",
                        "Neves Paulista", "Nhandeara", "Nova Granada",
                        "Nova Odessa", "Novo Horizonte", "Nuporanga",
                        "Olímpia", "Orlândia", "Osasco", "Osvaldo Cruz",
                        "Ourinhos", "Ouroeste", "Pacaembu", "Palestina",
                        "Palmeira D’Oeste", "Palmital", "Panorama",
                        "Paraguaçu Paulista", "Paraibuna", "Paranapanema",
                        "Pariquera-Açu", "Patrocínio Paulista", "Paulínia",
                        "Paulo de Faria", "Pederneiras", "Pedregulho",
                        "Pedreira", "Penápolis", "Penha", "Pereira Barreto",
                        "Peruíbe", "Piedade", "Pilar do Sul",
                        "Pindamonhangaba", "Pinhalzinho", "Pinheiros",
                        "Piquete", "Piracaia", "Piracicaba", "Piraju",
                        "Pirajuí", "Pirangi", "Pirapozinho", "Pirassununga",
                        "Piratininga", "Pitangueiras", "Poá", "Pompéia",
                        "Pontal", "Porangaba", "Porto Feliz", "Porto Ferreira",
                        "Potirendaba", "Praia Grande", "Presidente Bernardes",
                        "Presidente Epitácio", "Presidente Prudente",
                        "Presidente Venceslau", "Promissão", "Quatá", "Queluz",
                        "Rancharia", "Regente Feijó", "Registro",
                        "Ribeirão Bonito", "Ribeirão Pires", "Ribeirão Preto",
                        "Rio Claro", "Rio das Pedras", "Rio Grande de Serra",
                        "Rosana", "Roseira", "Salesópolis", "Salto",
                        "Salto de Pirapora", "Santa Adélia",
                        "Santa Bárbara D’Oeste", "Santa Branca",
                        "Santa Cruz das Palmeiras", "Santa Cruz do Rio Pardo",
                        "Santa Fé do Sul", "Santa Isabel", "Santana",
                        "Santana do Parnaíba", "Santa Rita do Passa Quatro",
                        "Santa Rosa do Viterbo", "Santo Amaro",
                        "Santo Anastácio", "Santo André",
                        "Santo Antônio de Posse", "Santos",
                        "São Bento do Sapucaí", "São Bernardo do Campo",
                        "São Caetano do Sul", "São Carlos",
                        "São João da Boa Vista", "São Joaquim da Barra",
                        "São José do Rio Pardo", "São José do Rio Preto",
                        "São José dos Campos", "São Luis do Paraitinga",
                        "São Manuel", "São Miguel Arcanjo",
                        "São Miguel Paulista", "São Paulo", "São Pedro",
                        "São Roque", "São Sebastião", "São Sebastião da Grama",
                        "São Simão", "São Vicente", "Serrana", "Serra Negra",
                        "Sertãozinho", "Socorro", "Sorocaba", "Sumaré",
                        "Suzano", "Tabapuã", "Tabatinga", "Taboão da Serra",
                        "Tambaú", "Tanabí", "Taquaritinga", "Taquarituba",
                        "Tatuapé", "Tatuí", "Taubaté", "Teodoro Sampaio",
                        "Tietê", "Tremembé", "Tupã", "Tupi Paulista",
                        "Ubatuba", "Urânia", "Urupês", "Valinhos",
                        "Valparaíso", "Vargem Grande do Sul",
                        "Vargem Grande Paulista", "Várzea Paulista",
                        "Vila Mimosa", "Vila Prudente", "Vinhedo", "Viradouro",
                        "Votorantim", "Votuporanga"]},
    "to": {"sigla": "TO", "nome": "Tocantis",
           "comarcas": ["Almas", "Alvorada", "Ananás", "Araguacema",
                        "Araguaçu", "Araguaína", "Araguatins", "Arapoema",
                        "Arraias", "Augustinópolis", "Aurora do Tocantins",
                        "Axixá do Tocantins", "Colinas do Tocantins",
                        "Colméia", "Cristalândia", "Dianópolis",
                        "Figueirópolis", "Filadélfia", "Formoso do Araguaia",
                        "Goiatins", "Guaraí", "Gurupi", "Itacajá",
                        "Itaguatins", "Miracema do Tocantins", "Miranorte",
                        "Natividade", "Novo Acordo", "Palmas", "Palmeirópolis",
                        "Paraíso do Tocantins", "Paranã", "Paripueira",
                        "Pedro Afonso", "Peixe", "Pium",
                        "Ponte Alta do Tocantins", "Porto Nacional",
                        "Taguatinga", "Tocantínia", "Tocantinópolis",
                        "Wanderlândia", "Xambioá"]},
}


def get_comarcas():
    """Retorna um dicionário de comarcas do Brasil agrupadas por UF"""
    return _comarcas


def get_comarcas_by_uf(sigla_uf):
    """Retorna um dicionário de comarcas da UF selecionada"""

    if sigla_uf is not None:
        return _comarcas.get(sigla_uf.lower()).get('comarcas')
